name: "Frogbot"
description: "Scan for vulnerabilities in GitHub repositories."
author: "JFrog"
inputs:
  command:
    description: "'before-scan' or 'scan-pull-request'"
    required: true
  version:
    description: "Frogbot version"
    default: "latest"
    required: false
runs:
  using: "node16"
  main: "action/lib/main.js"
branding:
  icon: "terminal"
  color: "green"
