name: "Frogbot by JFrog"
description: "Scan your pull requests with JFrog Xray for security vulnerabilities."
author: "JFrog"
inputs:
  version:
    description: "Frogbot version"
    default: "latest"
    required: false
runs:
  using: "node16"
  main: "action/lib/main.js"
branding:
  icon: "terminal"
  color: "green"
