# JFrog Frogbot Config file supports multiple repository configuration.
# It is important to note that 'scan-pull-request' and 'create-fix-pull-request' only work on a single repository, thus only the first repository in the configuration file will be used.
# Please use 'scan-pull-requests' command to apply the multiple repository configurations.

- repoName: "" # Repository name
  includeAllVulnerabilities: false # Displays all existing vulnerabilities, including the ones that were added by the pull request. (Default: false)
  FailOnSecurityIssues: true # Fails the Frogbot task if any security issue is found. (Default: true)
  jfrogProjectKey: "" # JFrog project key. Learn more about it here: https://www.jfrog.com/confluence/display/JFROG/Projects
  watches: # Xray Watches. Learn more about them here: https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches
    -
  projects: # List of package manager related projects (e.g. npm, pip, maven projects) with their relevant working directories, installation command, etc.
    - installCommandName: "" # Installation command (e.g. npm, maven, pip)
      installCommandArgs: # List of arguments to the installation command (e.g. install, i)
        -
      workingDirs: # List of relative path to the projects directories in the git repository (Default: root directory)
        - .
      pipRequirementsFile: # The requirements file name that used to install dependencies in case of pip package manager. ( pip install -r <JF_REQUIREMENTS_FILE> )
      useWrapper: true # Use Gradle Wrapper (gradlew/gradlew.bat) to run Gradle (default: true)