- params:
    git:
      repoName: frogbot
      branches:
        - dev
        - master
    scan:
      projects:
        - workingDirs:
            - .
        - installCommand: npm i
          workingDirs:
            - action