name: "Frogbot Scan and Fix"
on:
  push:
    branches:
      - "dev"
jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install prerequisites
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x

      - name: Build Frogbot
        run: buildscripts/build.sh
      - name: Scan
        env:
          JF_URL: ${{ secrets.FROGBOT_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: "dev"
          JF_GIT_PULL_REQUEST_ID: ${{ github.event.number }}
          JF_GIT_PROVIDER: "github"
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_REPO: ${{ github.event.repository.name }}
        run: ./frogbot create-fix-pull-requests
