name: "Go Tests"

on:
  push:
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [labeled]

# Ensures that only the latest commit is running for each PR at a time.
# Ignores this rule for push events.
concurrency:
  group: ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  bitbucket-server-integration:
    name: Bitbucket Server Integration Tests
    runs-on: ubuntu-latest
    container: atlassian/bitbucket-server:latest
    env:
      JFROG_CLI_LOG_LEVEL: "DEBUG"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Unzip Bitbucket Server
        run: |
          apt-get install zip unzip
          unzip testdata/resources/bitbucket_server.zip

      - name: Run Bitbucket Server container
        run: |
          chmod +x bitbucketServer
          docker run -v bitbucketServer:/var/atlassian/application-data/bitbucket --name="bitbucket" -d -p 7990:7990 -p 7999:7999 atlassian/bitbucket-server

      - name: Execute Go code inside the container
        run: |
          ./buildscripts/build.sh
          go test -v bitbucket_server_test.go commands.go main.go
