name: "Go Tests"

on:
  push:
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [labeled]

# Ensures that only the latest commit is running for each PR at a time.
# Ignores this rule for push events.
concurrency:
  group: ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  bitbucket-server-integration:
    name: Bitbucket Server Integration Tests
    runs-on: ubuntu-latest
    env:
      JFROG_CLI_LOG_LEVEL: "DEBUG"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Pull Bitbucket Server Docker image
        run: docker pull atlassian/bitbucket-server

      - name: Unzip Bitbucket Server
        run: unzip ${{ github.workspace }}/testdata/resources/bitbucket_server.zip

      - name: Run Bitbucket Server container
        run: |
          chmod +x bitbucketServer
          docker run -v bitbucketServer:/var/atlassian/application-data/bitbucket --name="bitbucket" -d -p 7990:7990 -p 7999:7999 atlassian/bitbucket-server

      - name: Wait for Bitbucket Server to finish loading
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost:7990/status"
          responseCode: 200
          timeout: 600000
          interval: 500

      - name: Execute Go code inside the container
        run: |
          ls -lsa
          docker cp ./ $(docker ps -q --filter "name=bitbucket"):/home/frogbot
          docker exec -it $(docker ps -qf "name=bitbucket") /bin/bash
          car /home/frogbot
          curl -fL https://golang.org/dl/go1.20.10.linux-amd64.tar.gz | tar -zxC /usr/local
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          go test -v bitbucket_server_test.go commands.go main.go
        env:
          JF_URL: ${{ secrets.PLATFORM_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.PLATFORM_ADMIN_TOKEN }}
          FROGBOT_TESTS_BB_SERVER_TOKEN: ${{ secrets.FROGBOT_TESTS_BB_SERVER_TOKEN }}
