name: "Test"

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Lint
        run: go vet ./...
      - name: Tests
        run: go test -v -race -timeout 0 -cover ./...
